apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: config-file
spec:
  version: "v0.1.0"       
  platforms:
  - selector:             
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    uri: https://github.com/Modulus/kubectl-cfg/archive/0.0.6.zip
    sha256: "325aa06035e07d6da42ee5c0e44b29b92990b3584589447dcf80b093114b0a43"
    files:
    - from: "/kubectl-config-file*/*.sh"
      to: "."              
    bin: "./kubectl-config-file.sh"  
  shortDescription: List available kubeconfigs and link them to ~/.kube/config.
  homepage: https://github.com/Modulus/kubectl-config-file
  description: |
    List available kubeconfigs and link them to ~/.kube/config. So you can work
    with multiple cluster configs without messing with environment variables.
