apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: config-file
spec:
  version: "v0.0.7"       
  platforms:
  - selector:             
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    uri: https://github.com/Modulus/kubectl-cfg/archive/0.0.6.zip
    sha256: "43a875916e78d3481cb06803d4e59a57d2e9c4d5c91e61e26a635fc6dceff46d"
    files:
    - from: "/kubectl-config-file*/*.sh"
      to: "."              
    bin: "./kubectl-config-file.sh"  
  shortDescription: List available kubeconfigs and link them to ~/.kube/config.
  homepage: https://github.com/Modulus/kubectl-cfg 
  description: |
    List available kubeconfigs and link them to ~/.kube/config. So you can work
    with multiple cluster configs without messing with environment variables.
