apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: config-file
spec:
  version: "v0.1.2"       
  platforms:
  - selector:             
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    uri: https://github.com/Modulus/kubectl-config-file/archive/v0.1.2.zip
    sha256: "9ee9aa2ac6510157d3531017aa6245e015bdd09f22da9a328109024cb62f76bc"
    files:
    - from: "/kubectl-config-file*/*.sh"
      to: "."              
    bin: "./kubectl-config-file.sh"  
  shortDescription: List available kubeconfigs and link them to ~/.kube/config.
  homepage: https://github.com/Modulus/kubectl-config-file
  description: |
    List available kubeconfigs and link them to ~/.kube/config. So you can work
    with multiple cluster configs without messing with environment variables.
