apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: config-file
spec:
  version: "v0.1.0"       
  platforms:
  - selector:             
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
    uri: https://github.com/Modulus/kubectl-config-file/archive/v0.1.1.zip
    sha256: "644ddfb07c89b567a47ae4786e151351cc46f5c86fad6f7537e83a9c3a347987"
    files:
    - from: "/kubectl-config-file*/*.sh"
      to: "."              
    bin: "./kubectl-config-file.sh"  
  shortDescription: List available kubeconfigs and link them to ~/.kube/config.
  homepage: https://github.com/Modulus/kubectl-config-file
  description: |
    List available kubeconfigs and link them to ~/.kube/config. So you can work
    with multiple cluster configs without messing with environment variables.
